### PR TITLE
[FIX] gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:84: invalid multibyte escape: /[\x80-\xFF]/

### PR DESCRIPTION
**Pull request by johnschult**
Added # encoding: BINARY to first line of extensions.rb

### CODE REVIEW

**Comment by johnschult** [comment]
The current release breaks under Ruby 1.9.2

**Comment by alexbhr** [comment]
+1 and amen to that one!

**Comment by fedegl** [comment]
Why hasn't this been merged in?

**Comment by lurchpop** [comment]
WTF! MAN!! This hasn't been fixed for 4 goddamn years

**Comment by ilias-t** [comment]
^Agreed, this is ridiculous.

**Comment by wesbaker999** [comment]
manually editing the fix submitted by johnschult worked for me

**Comment by gbrennon** [comment]
How can I manually edit this? As my rails app install everything on heroku via rake, I can't edit my production files

**Comment by dara** [comment]
@gbrennon if the app is using Paperclip you may simply replace 'aws-s3' gem with Paperclip's new default 'aws-sdk' in the gem file. It works automatically.

**Comment by cheshire137** [comment]
This worked for me to fix the error with my aws-s3-0.6.2 install that would abort my Rake tasks.

**Comment by johnschult** [comment]
This clearly got ignored...  too old now to merge 😏

**Pull request closed without merging**
