### PR TITLE
Remove undocumented, unnecessary const_missing_from_s3_library that broke my UserBucket model.

### PR DESCRIPTION
**Pull request by brandonbloom**
Hi Marcel,

I found this comment from you on the web:

"
Just to sanity check, you could go into lib/aws/s3/extensions.rb and 
remove
the definition to const_missing_from_s3_library and the two calls to
alias_method below it. I threw in that const missing recently just to 
add a
tiny convenience to the API. What it provides isn't even documented and 
the
library doesn't depend on it so you can safely take it away. I probably 
will
remove it. I was just trying it on to see how it felt. But either way, 
my
const_missing shouldn't be getting in the way since it's chaining back 
to the
original.
"

Source: http://www.ruby-forum.com/topic/89681

This little "convenience" led me on quite the interesting wild goose chase. I have a Rails model named Bucket and it is mapped by an association table to the User model. That association's name? UserBucket. Yeah, well, adding aw-s3 to my Gemfile caused all sorts of interestingly broken behavior. Since you yourself suggested that you may remove it, I've taken the liberty of doing it for you :-)

Thanks!
Brandon

### CODE REVIEW

**Comment by gtd** [comment]
+1 I've pulled Renato Correa's patch from Jan 2009 into my branch:
http://github.com/dasil003/aws-s3/commit/510af8b36f4da3f14d64810d7b54ff0ab74c3085

**Comment by joefiorini** [comment]
+1 I had a similar wild goose chase; lost a few hours to it. This falls under the "with great power comes great responsibility" clause of being a member of the Ruby community. I know we can modify the gem, but could you please remove this before someone else thinks its an example of good practice?

Thanks!

**Comment by joefiorini** [comment]
For anyone else who has a problem with this, I have forked Marcel's gem, removed the offending code and pushed it to rubygems. It's called jaf-s3. All the code is exactly the same except I removed the alias_method_chain and associated method. Feel free to use it, just know that I'm not supporting it :) I'm just using it until we can take some time to switch to Right AWS.

**Comment by monicao** [comment]
+1

**Comment by marcel** [comment]
While I agree that it's not worth keeping this behavior, simply removing it will break backwards compatibility. 

A safer approach perhaps would be to do something along the lines of putting this into an END block and before invoking it check ObjectSpace for any classes that match the pattern and if there are any don't define it and if there aren't, define it but enhance the implementation to print out a deprecation warning and also if ENV['RAILS_ENV'] is set to production don't define the code. 

I apologize to everyone who had to spend maddening hours hunting this down. What was added as a convenience ended up more often than not likely being anything but.

**Comment by brandonbloom** [comment]
Simpler is better: Move it to an external module & provide an option to enable this behavior if needed for compatibility. Document it as deprecated in the README.

**Comment by marcel** [comment]
That is simpler but breaks backwards compatibility without a deprecation. My first priority with the library is to have it remain stable. While I'm obviously not against improving it and enhancing it, I don't want to do that at the cost of causing failures in production. While failures in development are frustrating and I apologize, failures in production are worse. Sure people shouldn't just push a dependency upgrade into production without testing it first but the reality is that people do.

**Comment by brandonbloom** [comment]
... isn't that what SemVer and Gemfile.lock are for?

So whatever, add a deprecation warning & a way to turn it off. That would
have prevented the wild goose chase. At minimum add a note to the README
that this behavior exists.

**Comment by morten** [comment]
Any chance for a fix for this? A major version bump would work?

**Comment by amanfredi** [comment]
+1, tracking this down was super annoying, especially since the behavior depends on load order.

**Comment by brandonbloom** [comment]
Closing due to lack of interest and personal pull request cleanup. If anyone else wants this, maybe Marcel would be interested in a patch that adds a deprecation warning.

**Comment by jamesreggio** [comment]
+1

**Pull request closed without merging**
